import uuid from 'react-native-uuid';

const days = 30
const method = {
    credit: "Card - ****9876",
    debit: "Card - ****5432",
    bank: "Wire - ****9988",
    transfer: "Interac b***@y***o.com",
    cash: "Cash Payment",
    paypal: "PayPal - user@example.com",
    applePay: "Apple Pay - ****1234",
    googlePay: "Google Pay - ****5678",
    venmo: "Venmo - @user123",
    zelle: "Zelle - user@bank.com",
    cryptocurrency: "Crypto - Wallet Address",
    check: "Check - #123456",
    giftCard: "Gift Card - Balance $50",
    directDeposit: "Direct Deposit - Account #56789",
    wireTransfer: "Wire Transfer - Ref: 123ABC",
    mobilePayment: "Mobile Payment - App ID 98765",
}

const getRandomDate = () => {
    const days = 30; 
    return new Date(new Date().getTime() - (1000 * 60 * 60 * 24 * (Math.random() * days))).toISOString();
}

export default transactioManager = [
    {
        id: uuid.v4(),
        desc: "Amazon Purchase",
        category: "Shopping",
        amount: 59.99,
        date: getRandomDate(),
        paymentMethod: method.credit,
    },
    {
        id: uuid.v4(),
        desc: "Gym Membership",
        category: "Health",
        amount: 29.99,
        date: getRandomDate(),
        paymentMethod: method.debit,
    },
    {
        id: uuid.v4(),
        desc: "Movie Tickets",
        category: "Leisure",
        amount: 25.00,
        date: getRandomDate(),
        paymentMethod: method.cash,
    },
    {
        id: uuid.v4(),
        desc: "Gas Station",
        category: "Transportation",
        amount: 45.76,
        date: getRandomDate(),
        paymentMethod: method.debit,
    },
    {
        id: uuid.v4(),
        desc: "Monthly Rent",
        category: "Housing",
        amount: 1200.00,
        date: getRandomDate(),
        paymentMethod: method.bank,
    },
    {
        id: uuid.v4(),
        desc: "Dinner at Bistro",
        category: "Food",
        amount: 63.45,
        date: getRandomDate(),
        paymentMethod: method.credit,
    },
    {
        id: uuid.v4(),
        desc: "Online Course",
        category: "Education",
        amount: 199.99,
        date: getRandomDate(),
        paymentMethod: method.transfer,
    },
    {
        id: uuid.v4(),
        desc: "Concert Tickets",
        category: "Leisure",
        amount: 150.00,
        date: getRandomDate(),
        paymentMethod: method.cash,
    },
    {
        id: uuid.v4(),
        desc: "Grocery Store",
        category: "Groceries",
        amount: 85.50,
        date: getRandomDate(),
        paymentMethod: method.debit,
    },
    {
        id: uuid.v4(),
        desc: "Freelance Income",
        category: "Income",
        amount: 2000.00,
        date: getRandomDate(),
        paymentMethod: method.bank,
    },
    {
        id: uuid.v4(),
        desc: "Pet Supplies",
        category: "Pets",
        amount: 32.20,
        date: getRandomDate(),
        paymentMethod: method.credit,
    },
    {
        id: uuid.v4(),
        desc: "Monthly Subscription",
        category: "Entertainment",
        amount: 12.99,
        date: getRandomDate(),
        paymentMethod: method.transfer,
    },
    {
        id: uuid.v4(),
        desc: "Utilities Bill",
        category: "Services & utilities",
        amount: 95.23,
        date: getRandomDate(),
        paymentMethod: method.bank,
    },
    {
        id: uuid.v4(),
        desc: "New Shoes",
        category: "Shopping",
        amount: 120.00,
        date: getRandomDate(),
        paymentMethod: method.debit,
    },
    {
        id: uuid.v4(),
        desc: "Birthday Gift",
        category: "Gifts",
        amount: 50.00,
        date: getRandomDate(),
        paymentMethod: method.cash,
    },
];