import uuid from 'react-native-uuid';

const days = 30;
const method = {
    credit: "Card - ****9876",
    debit: "Card - ****5432",
    bank: "Wire - ****9988",
    transfer: "Interac b***@y***o.com",
    cash: "Cash Payment",
    paypal: "PayPal - user@example.com",
    applePay: "Apple Pay - ****1234",
    googlePay: "Google Pay - ****5678",
    venmo: "Venmo - @user123",
    zelle: "Zelle - user@bank.com",
    cryptocurrency: "Crypto - Wallet Address",
    check: "Check - #123456",
    giftCard: "Gift Card - Balance $50",
    directDeposit: "Direct Deposit - Account #56789",
    wireTransfer: "Wire Transfer - Ref: 123ABC",
    mobilePayment: "Mobile Payment - App ID 98765",
};

const getRandomDate = () => {
    return new Date(new Date().getTime() - (1000 * 60 * 60 * 24 * (Math.random() * days))).toISOString();
};

const transactioManager = [
    {
        id: uuid.v4(),
        desc: "Amazon Purchase",
        category: "Shopping",
        amount: 59.99,
        date: getRandomDate(),
        paymentMethod: method.credit,
        location: "Online",
        transactionId: "TXN123456",
        status: "Completed",
        currency: "USD",
        notes: "Gift for friend",
    },
    {
        id: uuid.v4(),
        desc: "Gym Membership",
        category: "Health",
        amount: 29.99,
        date: getRandomDate(),
        paymentMethod: method.debit,
        location: "Local Gym",
        transactionId: "TXN123457",
        status: "Completed",
        currency: "USD",
        notes: "Monthly fee",
    },
    {
        id: uuid.v4(),
        desc: "Movie Tickets",
        category: "Leisure",
        amount: 25.00,
        date: getRandomDate(),
        paymentMethod: method.cash,
        location: "Cinema",
        transactionId: "TXN123458",
        status: "Completed",
        currency: "USD",
        notes: "Date night",
    },
    {
        id: uuid.v4(),
        desc: "Gas Station",
        category: "Transportation",
        amount: 45.76,
        date: getRandomDate(),
        paymentMethod: method.debit,
        location: "Shell Gas Station",
        transactionId: "TXN123459",
        status: "Completed",
        currency: "USD",
        notes: "Fuel for the car",
    },
    {
        id: uuid.v4(),
        desc: "Monthly Rent",
        category: "Housing",
        amount: 1200.00,
        date: getRandomDate(),
        paymentMethod: method.bank,
        location: "Apartment Complex",
        transactionId: "TXN123460",
        status: "Completed",
        currency: "USD",
        notes: "Rent for March",
    },
    {
        id: uuid.v4(),
        desc: "Dinner at Bistro",
        category: "Food",
        amount: 63.45,
        date: getRandomDate(),
        paymentMethod: method.credit,
        location: "Bistro Café",
        transactionId: "TXN123461",
        status: "Completed",
        currency: "USD",
        notes: "Dinner with family",
    },
    {
        id: uuid.v4(),
        desc: "Online Course",
        category: "Education",
        amount: 199.99,
        date: getRandomDate(),
        paymentMethod: method.transfer,
        location: "Online",
        transactionId: "TXN123462",
        status: "Completed",
        currency: "USD",
        notes: "Web development course",
    },
    {
        id: uuid.v4(),
        desc: "Concert Tickets",
        category: "Leisure",
        amount: 150.00,
        date: getRandomDate(),
        paymentMethod: method.cash,
        location: "Stadium",
        transactionId: "TXN123463",
        status: "Completed",
        currency: "USD",
        notes: "Concert with friends",
    },
    {
        id: uuid.v4(),
        desc: "Grocery Store",
        category: "Groceries",
        amount: 85.50,
        date: getRandomDate(),
        paymentMethod: method.debit,
        location: "Local Grocery",
        transactionId: "TXN123464",
        status: "Completed",
        currency: "USD",
        notes: "Weekly groceries",
    },
    {
        id: uuid.v4(),
        desc: "Freelance Income",
        category: "Income",
        amount: 2000.00,
        date: getRandomDate(),
        paymentMethod: method.bank,
        location: "N/A",
        transactionId: "TXN123465",
        status: "Completed",
        currency: "USD",
        notes: "Payment for services",
    },
    {
        id: uuid.v4(),
        desc: "Pet Supplies",
        category: "Pets",
        amount: 32.20,
        date: getRandomDate(),
        paymentMethod: method.credit,
        location: "Pet Store",
        transactionId: "TXN123466",
        status: "Completed",
        currency: "USD",
        notes: "Food and toys for pet",
    },
    {
        id: uuid.v4(),
        desc: "Monthly Subscription",
        category: "Entertainment",
        amount: 12.99,
        date: getRandomDate(),
        paymentMethod: method.transfer,
        location: "Online",
        transactionId: "TXN123467",
        status: "Completed",
        currency: "USD",
        notes: "Streaming service",
    },
    {
        id: uuid.v4(),
        desc: "Utilities Bill",
        category: "Services & utilities",
        amount: 95.23,
        date: getRandomDate(),
        paymentMethod: method.bank,
        location: "Online",
        transactionId: "TXN123468",
        status: "Completed",
        currency: "USD",
        notes: "Electricity bill",
    },
    {
        id: uuid.v4(),
        desc: "New Shoes",
        category: "Shopping",
        amount: 120.00,
        date: getRandomDate(),
        paymentMethod: method.debit,
        location: "Shoe Store",
        transactionId: "TXN123469",
        status: "Completed",
        currency: "USD",
        notes: "Running shoes",
    },
    {
        id: uuid.v4(),
        desc: "Birthday Gift",
        category: "Gifts",
        amount: 50.00,
        date: getRandomDate(),
        paymentMethod: method.cash,
        location: "Online",
        transactionId: "TXN123470",
        status: "Completed",
        currency: "USD",
        notes: "Gift for friend’s birthday",
    },
];

export default transactioManager;